---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# feowR

<!-- badges: start -->
<!-- badges: end -->

The goal of **feowR** is to download shapefiles of Freshwater Ecoregions of the World (FEOW) inside R

## Installation

You can install the development version of feowR from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("brunomioto/feowR")
```

## Example


```{r example}
library(feowR)

feow_sf <- read_feow()
```

Now let's plot it!

```{r, dpi=600,warning=FALSE}
library(ggplot2)

ggplot(data = feow_sf)+
  geom_sf()
```

We can see the list of all ecoregions, from [FEOW website](https://www.feow.org/ecoregions/list)

```{r}
ecoregions_list
```


Look the Freshwater Ecoregions of Neotropical region!

```{r, dpi = 600, warning=FALSE, message=FALSE}
library(dplyr)

feow_sf |>
  left_join(ecoregions_list, by = join_by("FEOW_ID" == "id")) |>
  filter(realm == "Neotropic") |>
  ggplot()+
  geom_sf()
```

